// Generated by CoffeeScript 1.3.3
(function() {
  var _this = this;

  describe('Backbone.StateManager.States', function() {
    beforeEach(function() {
      return _this._states = _.clone(spec.helper.states);
    });
    afterEach(function() {
      return delete _this._states;
    });
    describe('constructor', function() {
      return it('creates a regexp of the name', function() {
        var state;
        state = new Backbone.StateManager.State('foo', {});
        return expect(state.regExpName).toBeDefined();
      });
    });
    return describe('prototype', function() {});
  });

}).call(this);
