// Generated by CoffeeScript 1.3.3
(function() {

  window.spec = {
    helper: {
      states: {
        noTransitions: {
          enter: function() {},
          exit: function() {}
        },
        withInitial: {
          initial: true,
          enter: function() {},
          exit: function() {}
        },
        nonMethodExit: {
          enter: function() {},
          exit: {}
        },
        nonMethodEnter: {
          enter: {},
          exit: function() {}
        }
      }
    }
  };

}).call(this);
